apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-webhook-from-apiserver
  namespace: external-secrets
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-webhook
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.16.0.0/28   # GKE control plane CIDR (master endpoint)
        - ipBlock:
            cidr: 10.20.0.0/16    # GKE pod CIDR
        - ipBlock:
            cidr: 10.10.0.0/22    # GKE nodes CIDR
      ports:
        - protocol: TCP
          port: 10250
