apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-managed
  namespace: kafka-operator
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kafka
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-managed
  namespace: cnpg-system
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: postgres
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-webhook-from-apiserver
  namespace: cnpg-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.16.0.0/28   # GKE control plane CIDR
        - ipBlock:
            cidr: 10.20.0.0/16    # GKE pod CIDR
        - ipBlock:
            cidr: 10.10.0.0/22    # GKE nodes CIDR
      ports:
        - protocol: TCP
          port: 9443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-cluster
  namespace: cert-manager
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-webhook-from-apiserver
  namespace: cert-manager
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: webhook   # cert-manager-webhook label
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 172.16.0.0/28   # GKE control plane CIDR
        - ipBlock:
            cidr: 10.20.0.0/16    # GKE pod CIDR
        - ipBlock:
            cidr: 10.10.0.0/22    # GKE nodes CIDR
      ports:
        - protocol: TCP
          port: 10250
