fullnameOverride: reader

image:
  tag: "0.1.0"

imagePullSecrets:
  - name: registry-pull

env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATASOURCE_URL: jdbc:postgresql://demo-pg-r.postgres.svc.cluster.local:5432/app?ssl=true&sslmode=require

envFromSecrets:
  - postgres-creds

ingress:
  enabled: true
  hostname: reader

networkPolicies:
  allowIngressFromNginx: true
  egressAllows:
    - name: postgres
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: postgres
      ports:
        - protocol: TCP
          port: 5432

