fullnameOverride: front

image:
  tag: "0.1.0"

imagePullSecrets:
  - name: registry-pull

env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_KAFKA_BOOTSTRAP_SERVERS: demo-kafka-bootstrap.kafka.svc.cluster.local:9093
  SPRING_KAFKA_SECURITY_PROTOCOL: SSL
  SPRING_KAFKA_SSL_TRUST_STORE_LOCATION: file:/etc/kafka/ca.p12
  SPRING_KAFKA_SSL_TRUST_STORE_TYPE: PKCS12
  SPRING_KAFKA_SSL_KEY_STORE_LOCATION: file:/etc/kafka/user.p12
  SPRING_KAFKA_SSL_KEY_STORE_TYPE: PKCS12

envFromSecrets:
  - kafka-front-passwords

volumes:
  - name: kafka-certs
    secret:
      secretName: kafka-front-certs
      items:
        - key: user.p12
          path: user.p12
        - key: ca.p12
          path: ca.p12
volumeMounts:
  - name: kafka-certs
    mountPath: /etc/kafka
    readOnly: true

ingress:
  enabled: true
  hostname: front

networkPolicies:
  allowIngressFromNginx: true
  egressAllows:
    - name: kafka
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kafka
      ports:
        - protocol: TCP
          port: 9093

externalSecrets: []   # populated in Sprint 4d (cross-ns sync)
