nameOverride: ""
fullnameOverride: ""

image:
  repository: REPLACE-ME-via-helm-set
  tag: "0.1.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []

replicaCount: 1

ports:
  http: 8080
  management: 8081

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 5
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 30

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 768Mi

env: {}

envFromSecrets: []

volumes: []
volumeMounts: []

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: nginx
  hostname: ""
  baseDomain: REPLACE-ME-via-helm-set
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

externalSecrets: []

networkPolicies:
  allowIngressFromNginx: false
  egressAllows: []

podSecurityContext:
  runAsUser: 65532
  runAsGroup: 65532
  runAsNonRoot: true
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  runAsUser: 65532
  runAsGroup: 65532
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault

serviceAccount:
  create: true
  name: ""    # default: chart fullname
