apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm
spec:
  provider:
    gcpsm:
      projectID: PROJECT_ID_FROM_TF
      auth:
        workloadIdentity:
          clusterLocation: CLUSTER_LOCATION_FROM_TF
          clusterName: CLUSTER_NAME_FROM_TF
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
