apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-front-certs
  namespace: demo-front
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kafka-secrets
    kind: ClusterSecretStore
  target:
    name: kafka-front-certs
    creationPolicy: Owner
  data:
    - secretKey: user.p12
      remoteRef:
        key: front
        property: user.p12
    - secretKey: ca.p12
      remoteRef:
        key: demo-cluster-ca-cert
        property: ca.p12
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-front-passwords
  namespace: demo-front
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kafka-secrets
    kind: ClusterSecretStore
  target:
    name: kafka-front-passwords
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SPRING_KAFKA_SSL_KEY_STORE_PASSWORD: "{{ .userPassword }}"
        SPRING_KAFKA_SSL_KEY_PASSWORD: "{{ .userPassword }}"
        SPRING_KAFKA_SSL_TRUST_STORE_PASSWORD: "{{ .caPassword }}"
  data:
    - secretKey: userPassword
      remoteRef:
        key: front
        property: user.password
    - secretKey: caPassword
      remoteRef:
        key: demo-cluster-ca-cert
        property: ca.password
