apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lab-ca
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cert-manager-secrets
    kind: ClusterSecretStore
  target:
    name: lab-ca
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: lab-ca-secret
        property: ca.crt
