---
all:
  children:
    k3s_cluster:
      children:
        k3s_server:
          hosts:
            box-1:
              ansible_host: 192.168.10.51   # control-plane node IP
              k3s_role: server
        k3s_agent:
          hosts:
            box-2:
              ansible_host: 192.168.10.52
              k3s_role: agent
            box-3:
              ansible_host: 192.168.10.53
              k3s_role: agent
      vars:
        cluster_kind: kubernetes
