---
all:
  children:
    k3s_cluster:
      children:
        k3s_server:
          hosts:
            box-1:
              ansible_host: 192.168.10.51   # control-plane node IP
              k3s_role: server
        k3s_agent:
          hosts: {}
      vars:
        cluster_kind: kubernetes
