apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  duration: 8760h     # 1 year — rotation handled by cert-manager renewBefore
  renewBefore: 720h   # renew 30 days before expiry
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  dnsNames:
    - vault
    - vault.vault
    - vault.vault.svc
    - vault.vault.svc.cluster.local
    - vault-0.vault-internal
    - vault-0.vault-internal.vault.svc.cluster.local
    - localhost   # for in-pod CLI calls (VAULT_ADDR=https://127.0.0.1:8200)
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: lab-ca
    kind: ClusterIssuer
    group: cert-manager.io
